Container
Kn0wl3dge/mozitools pull request #3
Opened 2022-10-26 19:32 UTC by gachampiat

Hi,

This PR adds a Containerfile to try out this project.
It also adds a docker-compose file to deploy an elk

2022-10-26 20:29 UTC, kn0wl3dge requested changes
Hi @gachampiat,

Here is some feedback before I can fully merge this PR.
Thanks for your help.

2022-10-26 20:29 UTC, kn0wl3dge commented on README.md
> +
The Mozi release can be used in the first place in a simpler way (just get the release for your arch and run it).   
However running this tool in a container is still interesting for people looking for more isolation.

```suggestion
You can download and try the latest release on the [release page](https://github.com/kn0wl3dge/mozitools/releases).

The binaries are self sufficient. 
However, if you want to run this tool in a more isolated way you can use the provided Container file.
```

2022-10-26 20:29 UTC, kn0wl3dge commented on README.md
> +To create the image :
```suggestion
Execute the following command to create the image:   
```

2022-10-26 20:29 UTC, kn0wl3dge commented on README.md
> +To test Mozitools :
```suggestion
You are now able to run Mozitools from the previously built image:  
```

2022-10-26 20:29 UTC, kn0wl3dge commented on README.md
> +To deploy the stack a docker-compose is available.
```suggestion
To deploy the stack a docker-compose is available if you're looking to try the Mozi tracker. Please be aware that it is not intended and clearly unsafe for production usage.
```

2022-10-26 20:29 UTC, kn0wl3dge commented on docker-compose.yaml
> +    image: elasticsearch:7.17.6
Is there a particular reason associated to this version choice?

2022-10-27 19:41 UTC, gachampiat commented on docker-compose.yaml
> +    image: elasticsearch:7.17.6
Yes, because higher versions do not allow to use the elastic user, as the aim of this docker-compose is only to try out the track function I have supposed it's not an issue to not use the latest grafana tag. It's ok for u ?

2022-10-27 20:20 UTC, kn0wl3dge commented on docker-compose.yaml
> +    image: elasticsearch:7.17.6
It's okay for me then. :)  However, since the Elastic component is only needed for Mozi Tracker, could you add another container that runs the mozi tracker.

2022-10-27 21:41 UTC, kn0wl3dge requested changes

2022-10-27 21:41 UTC, kn0wl3dge commented on docker-compose.yaml
> +    image: mozitools
```suggestion
    image: mozitools
    build:
      context: .
      dockerfile: Containerfile
```
This way, the mozitools image will be automatically built if it does not exists.

2022-10-27 21:41 UTC, kn0wl3dge commented on README.md
> +*Note: Do not forget to build the image for docker !*
With the docker-compose update, this line won't be needed anymore

2022-10-27 21:41 UTC, kn0wl3dge commented on docker-compose.yaml
> +    environment:
We could add a volume here so the data persists on the system.

2022-10-27 21:42 UTC, kn0wl3dge approved these changes

2022-10-27 21:42 UTC, kn0wl3dge commented on docker-compose.yaml
> +        retries: 5
This is really nice!

2022-11-13 15:26 UTC, merged